### PR TITLE
Enable unified_mode for Chef 17 compatibility

### PR DESCRIPTION
**Pull request by detjensrobert**
Signed-off-by: Robert Detjens <detjensrobert@osuosl.org>

# Description

Enable `unified_mode` for Chef 17 compatibility.

Major bump as this bumps the required Chef version to 15.3.

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by Xorima — DISMISSED** [review]

**Comment by detjensrobert** [comment]
Would you like me to write Inspec tests as part of this PR? Currently there are no tests, just the converge.

**Comment by ramereth** [comment]
@detjensrobert you might as well add it on this PR

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [4.0.0](https://github.com/sous-chefs/nrpe/releases/tag/4.0.0)

**Pull request merged**
