### PR TITLE
Add disable_search attribute

### PR DESCRIPTION
**Pull request by kamaradclimber**
This will avoid querying chef servers on infrastructure where it is not
relevant (for those using allowed_hosts directly for instance)

Change-Id: Idf42aeaa85b2e7cb2894b118aedc49ee36813ec5

### CODE REVIEW

**Comment by kamaradclimber** [comment]
@tas50 would you have feedback on that PR?

**Comment by damacus** [comment]
We should be removing the Chef solo specific behaviour here. Instead of augmenting it. Seeing as search actually works now.

**Comment by damacus** [comment]
Hey @kamaradclimber do you still want this PR or are we good to close it?

**Comment by kamaradclimber** [comment]
Honestly i've used a fork for a long time now and now going away from nrpe
so feel free to close the pr

**Comment by damacus** [comment]
OK thanks!

**Pull request closed without merging**
